---
telegram:
  token: token
  admin_id: admin_id
  proxies:
    https: 'https://{name}:{pass}@{ip}:{port}'

transmission:
  address: 192.168.122.16
  user: False
  password: False

directories:
  global: '/'

commands:
  "/help":
    message: |
      /status: Статус закачек
      /info: Информация свободном месте
      magnet....: Начнется скачивание торрента
  "/status": torrent_status
  "/info": torrent_server_info
  "(?P<magnet>magnet.+)": add_torrent
  "ip a":
    shell: "ip a"